accounts/urls.py
"""
	Accountsアプリ
	URL定義

	Filename   urls.py
	Date: 2020.2.16
	Written by Takato Suzuki
"""

from django.urls import path
from . import views

app_name = 'accounts'   # アプリケーション名
urlpatterns = [
	#'prfile'はURLリンクのパスを書いている。
	path('profile/<int:pk>', views.UserDetail.as_view(), name='user_detail'),
	path('profile/update/<int:pk>', views.UserUpdate.as_view(), name='user_update'),
	#PasswordChangeViewとPasswordChangeDoneViewはDjangoのアカウント機能にあるやつ
	path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
	path('password_change/done/', views.PasswordChangeDoneView.as_view(), name=('password_change_done')),
	path('create/',views.UserCreate.as_view(), name='user_create'),
]

blog/urls.py
"""
    Blogアプリ
    URL定義

    Filename   urls.py
    Date: 2022.4.21
    Written by Takato Suzuki

"""
from django.urls import path
from . import views

app_name = 'blog'   # アプリケーション名
urlpatterns = [
	path('', views.post_list, name='post_list'),
	path('post/<int:pk>/', views.post_detail, name='post_detail'),
	path('post/add/', views.PostCreateView.as_view(), name='post_add'),
	path('post/review', views.PostReviewListView.as_view(),name='post_review'),
	path('post/<int:pk>/publish', views.PublishRedirectView.as_view(),name='publish'),
	path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
	path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

project1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('blog.urls')),
	path('accounts/', include('accounts.urls')),
	path('accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
"""
    Blogアプリ
    データモデル

    Filename models.py
    Date:2022.4.21
    Written by Takato Suzuki

"""
from django.db import models
from django.conf import settings
from django.utils import timezone

class Post(models.Model):
    """
        ブログ記事クラス

        author  : 作者（Djangoのユーザモデル）
        title   :ブログのタイトル
        text    :ブログ本文
        create_date:作成日
        published_date:公開日

    """
    # フィールドの定義
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

accounts/forms.py
"""
	Accounts　更新フォームの定義

	Filename   forms.py
	Date: 2022.9.27
	Written by Takato Suzuki

"""
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserUpdateForm(ModelForm):
	"""ユーザー情報更新フォーム"""
	class Meta:
		model = User
		fields = ('last_name', 'first_name',)

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in self.fields.values():
			#'form-control'はbootstrapの属性を追加している。
			field.widget.attrs['class'] = 'form-control'

class UserCreateForm(UserCreationForm):
	"""
		ユーザー作成用のフォーム
	"""
	class Meta(UserCreationForm.Meta):
		#パスワードは指定しなくともデフォルトで追加される。
		fields = ('username', 'email')

blog/forms.py
"""
	Blogアプリ
	フォームクラス（データを入力を受けるためのクラス）

	Filename   forms.py
	Date: 2022.10.11
	Written by Takato Suzuki

"""
from django.forms import ModelForm
from django import forms
from .models import Post

class PostForm(ModelForm):
	"""
		記事登録画面用のフォーム
		title  : ブログのタイトル
		text   : ブログ本文
	"""
	class Meta:
		#  モデルクラスを指定
		model = Post
		#  モデルフィールドを指定
		fields = ("title", "text")
		labels = {
			'title': 'タイトル',
			'text': '本文',
		}

class PostSearchForm(forms.Form):
	"""
		記事検索用のフォーム
	"""
	key_word = forms.CharField(label='検索キーワード', required=False)

accounts/views.py
"""
	Accounts　表示部分

	Filename   views.py
	Date: 2022.9.27
	Written by Takato Suzuki

"""
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.views.generic import DetailView, UpdateView, CreateView
from django.shortcuts import resolve_url
from .forms import UserUpdateForm, UserCreateForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy

#UserPassesTestMixin　ユーザがある条件をパスしているかをテストための機能
#同じ処理を２つのビューで追加するために作成
class OnlyYouMixin(UserPassesTestMixin):
	raise_exception = True

	#テストをする関数でUserPassesTestMixinクラスの機能
	def test_func(self):
		"""
			ユーザがページのIDと一致する場合とスーパーユーザの場合許可する
		"""
		user = self.request.user
		return user.pk == self.kwargs['pk'] or user.is_superuser


class UserDetail(OnlyYouMixin, DetailView):
	"""
		ユーザの詳細を表示するビュー
	"""
	model = User	#models.pyのクラスを指定するが、今回はDjangoのUserをimportして使っている。
	template_name = 'accounts/user_detail.html'



#UpdateViewは既存のオブジェクトを変更する
class UserUpdate(OnlyYouMixin, UpdateView):
	"""
		ユーザデータの更新をするためのビュー
	"""
	model = User
	form_class = UserUpdateForm	#forms.pyのクラスを指定する。modelの役割
	template_name = 'accounts/user_form.html'

	def get_success_url(self):
		"""
			更新成功後の表示をする画面。ユーザの詳細を表示する画面に遷移する。
		"""
		return resolve_url('accounts:user_detail', pk=self.kwargs['pk'])

#CreateViewは新しいオブジェクトを作成する。
class UserCreate(CreateView):
	"""
		ユーザー作成用のビュー
	"""
	template_name = "registration/user_create.html"
	form_class = UserCreateForm
	success_url = reverse_lazy('login')

blog/views.py
"""
	Blogアプリ
	表示用の機能作成

	Filename   views.py
	Date: 2022.9.27
	Written by Shinsuke Kobayashi

"""
from django.shortcuts import render, reverse, get_object_or_404
from django.views.generic import View,DetailView, CreateView, RedirectView, UpdateView, DeleteView, ListView
from django.utils import timezone
from .models import Post
from .forms import PostForm, PostSearchForm
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from .mixins import CheckPermissionMixin

class PostListView(ListView):
	"""
		Get request 用の処理
		ブログ記事一覧を表示する
	"""
	model = Post
	template_name = 'blog/post_list.html'
	paginate_by = 3

	def get_queryset(self):
		"""
			検索条件の設定
		"""
		# フォームを設定
		form = PostSearchForm(self.request.GET or None)
		self.form = form

		# フォームが指定したキーワードを取得
		queryset = super().get_queryset()
		if form.is_valid():
			key_word = form.cleaned_data.get('key_word')
			if key_word:
				for word in key_word.split():
					queryset = queryset.filter(Q(title__icontains=word) | Q(text__icontains=word))

		# 記事データを取得
		queryset = queryset.filter(published_date__lte=timezone.now()).order_by('published_date')
		return queryset

	def get_context_data(self, **kwargs):
		"""
			コンテキストの設定
		"""
		context = super().get_context_data(**kwargs)
		context['form'] = self.form
		return context

post_list = PostListView.as_view()

class PostDetailView(CheckPermissionMixin,DetailView):
	model = Post
	template_name = "blog/post_detail.html"

post_detail = PostDetailView.as_view()

class PostCreateView(LoginRequiredMixin, CreateView):
	"""
		ブログ記事作成用のビュー
	"""
	model = Post							# 対象とするモデル
	form_class = PostForm				   # 使用するフォームクラス
	template_name = "blog/post_add.html"	# テンプレート

	def form_valid(self, form):
		# ユーザを追加
		form.instance.author = self.request.user

		return super().form_valid(form)

	def get_success_url(self):
		""" 詳細画面にリダイレクトする """
		return reverse('blog:post_detail', args=(self.object.id,))

class PostReviewListView(LoginRequiredMixin, View):
	"""
		下書き一覧のページ
	"""
	def get(self, request, *args, **kwargs):
		"""
			ブログの下書き記事一覧を表示する
		"""
		context = {}
		#  記事データを取得
		posts = Post.objects.filter(author=self.request.user, published_date__isnull=True).order_by('create_date')
		context['posts'] = posts
		return render(request, "blog/review_list.html", context)

class PublishRedirectView(LoginRequiredMixin, RedirectView):
	"""
		詳細ページでpublishに変更するボタンを押したときにリダイレクトして一覧に戻す
	"""
	pattern_name = 'blog:post_detail'

	def get_redirect_url(self, *args, **kwargs):
		post = get_object_or_404(Post, pk=kwargs['pk'])
		post.publish()
		return super().get_redirect_url(*args, **kwargs)

class PostUpdateView(LoginRequiredMixin, UpdateView):
	"""
		変更ページのビュー
	"""
	model = Post
	form_class = PostForm
	template_name = 'blog/post_update.html'

	# 更新が終了した時に表示する
	def get_success_url(self):
		"""詳細画面にリダイレクトする"""
		#object.idは記事番号
		#reverseはURLを逆引きする関数
		return reverse('blog:post_detail', args=(self.object.id,))

class PostDeleteView(LoginRequiredMixin, DeleteView):
	"""
		削除用のビュー
	"""
	model = Post
	template_name = 'blog/post_delete.html'
	def get_success_url(self):
		"""一覧ページにリダイレクトする"""
		return reverse('blog:post_list')

accounts/templates/accounts/user_detail.html
{% extends "blog/base.html" %}
{% block content %}
<table class="table">
		<tbody>
				<tr>
						<th>ユーザー名</th>
						<td>{{ user.email }}</td>
				</tr>
				<tr>
						<th>姓</th>
						<td>{{ user.last_name }}</td>
				</tr>
				<tr>
						<th>名</th>
						<td>{{ user.first_name }}</td>
				</tr>
		</tbody>
</table>
<a href="{% url 'accounts:password_change' %}" class="btn btn-success btn-lg">パスワード変更</a>
<a href="{% url 'accounts:user_update' user.pk %}" class="btn btn-success btn-lg">ユーザー情報変更</a>
{% endblock %}

accounts/templates/accounts/user_form.html
{% extends "blog/base.html" %}
{% block content %}
<form action="" method="POST">
		{{ form.non_field_errors }}
		<table class="table">
				<tbody>
						{% for field in form %}
								<tr>
										<th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
										<td>{{ field }} {{ field.errors }}</td>
								</tr>
						{% endfor %}
				</tbody>
		</table>
		{% csrf_token %}
		<button type="submit" class="btn btn-success btn-lg" >送信</button>
</form>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
{% load bootstrap4 %}
<html>
	<head>
		{% bootstrap_css %}
		{% bootstrap_javascript jquery='slim' %}
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
		<link rel="stylesheet" href="{% static 'css/blog.css' %}">
	</head>

	<body>
		<nav class="navbar navbar-expand-lg navbar-light">
			{% if user.is_authenticated %}
				<a class="navbar-brand" href="/"> {{user.username}}のブログ！</a>
			{% else %}
				<a class="navbar-brand" href="/">俺のブログ！</a>
			{% endif %}
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarNavDropdown">
				<ul class="navbar-nav mr-auto">
					<!--	左にメニューを出すとき -->
				</ul>

				<ul class="navbar-nav">
					<!--	右にメニューを出すとき -->
					{% if user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'blog:post_review' %}">下書き一覧</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'accounts:user_detail' user.pk %}">ユーザー情報閲覧</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
					</li>
					{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'accounts:user_create' %}">サインアップ</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'login' %}">ログイン</a>
					</li>
					{% endif %}
				</ul>
			</div>
		</nav>

		<div class="content container">
				<div class="row">
						<div class="col-md-8">
							{% block content %}
							{% endblock %}
						</div>
				</div>
		</div>
	</body>
</html>

blog/templates/blog/page.html
{% load blog_extras %}

<ul class="pagination">
	<!-- 前へ の部分 -->
	{% if page_obj.has_previous %}
		<li class="page-item">
			<a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">
				<span aria-hidden="true">&laquo;</span>
			</a>
		</li>
	{% endif %}

	<!-- 数字の部分 -->
	{% for num in page_obj.paginator.page_range %}
		{% if page_obj.number == num %}
			<li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
		{% else %}
			<li class="page-item"><a class="page-link" href="?{% url_replace request 'page' num %}">{{ num }}</a></li>
		{% endif %}
	{% endfor %}

	<!-- 次へ の部分 -->
	{% if page_obj.has_next %}
		<li class="page-item">
			<a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">
				<span aria-hidden="true">&raquo;</span>
			</a>
		</li>
	{% endif %}
</ul>

blog/templates/blog/post_add.html
{% extends 'blog/base.html' %}
{% load bootstrap4 %}

{% block content %}
	<form method="post">
		{% csrf_token %}
		{% bootstrap_form_errors form type='non_fields' %}
		{% bootstrap_field form.title placeholder='タイトル' %}
		{% bootstrap_field form.text placeholder='本文' %}
		<button type="submit" class="btn btn-primary btn-lg">作成</button>
	</form>
{% endblock %}

blog/templates/blog/post_delete.html
{% extends 'blog/base.html' %}
{% load bootstrap4 %}
{% load blog_extras %}

{% block content %}
	<form method="post">
		{% csrf_token %}
		<p>削除しても良いですか？</p>
		<button type="submit" class="btn btn-danger btn-lg">削除</button>
	</form>
	<div class="mt-3 mt-5">
		<a class="btn btn-primary btn-lg" href="{% get_return_link request %}">戻る</a>
	</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
		<div class="post">
			{% if post.published_date %}
				<div class="date">
					{{ post.published_date }}
				</div>
			{% endif %}
			<h2>{{ post.title }}</h2>
			<p>{{ post.text|linebreaksbr }}</p>
		</div>
		{% if post.author == user %}
		<div class="mt-3 mb-5">
			{% if not post.published_date %}
			<a class="btn btn-primary btn-lg" href="{% url 'blog:publish' post.pk %}">公開</a>
			{% endif %}
			<a class="btn btn-primary btn-lg" href="{% url 'blog:post_update' post.pk %}">変更</a>
			<a class="btn btn-danger btn-lg" href="{% url 'blog:post_delete' post.pk %}">削除</a>
		</div>
		{% endif %}
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
<form id="form" action="" method="GET">
	{{ form.key_word}}
		<button type="submit" class="btn btn-primary btn-lg">検索</button>
</form>

{% for post in post_list %}
	<div class="post">
		<p class="date">published: {{ post.published_date}}, by:{{ post.author.username }}</p>
		<h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
		<p>{{ post.text|linebreaksbr }}</p>
	</div>
{% endfor %}

{% include 'blog/page.html' %}
{% endblock %}

blog/templates/blog/post_list2.html
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  </head>

  <body>
    <div>
      <h1><a href="/">俺のブログ！</a></h1>
    </div>
    {% for post in posts %}
      <div>
          <p>published: {{ post.published_date}}</p>
          <h2><a href="">{{ post.title }}</a></h2>
          <p>{{ post.text|linebreaksbr }}</p>
      </div>
    {% endfor %}
  </body>
</html>

blog/templates/blog/post_update.html
{% extends 'blog/base.html' %}
{% load bootstrap4 %}

{% block content %}
	<form method="post">
		{% csrf_token %}
		{% bootstrap_form_errors form type='non_fields' %}
		{% bootstrap_field form.title placeholder='タイトル' %}
		{% bootstrap_field form.text placeholder='本文' %}
		<button type="submit" class="btn btn-primary btn-lg">変更</button>
	</form>
{% endblock %}

blog/templates/blog/review_list.html
{% extends 'blog/base.html' %}

{% block content %}
	<h1 class="mt-3 mb-5">下書き一覧</h1>
	{% for post in posts %}
		<div class="post">
			<p class="date">作成日: {{ post.create_date}}</p>
			<h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
			<p>{{ post.text|linebreaksbr }}</p>
		</div>
	{% endfor %}
	<div class="mt-3 mb-5">
		<a class="btn btn-primary btn-lg" href="{% url 'blog:post_add' %}">新規作成</a>
	</div>
{% endblock %}